/**
 * English Keyword Mappings for Icon Matcher
 * English translations and synonyms for AAC communication
 */

export const KEYWORD_MAP_EN: Record<string, string[]> = {
  // Needs - expanded
  'eat': ['eat', 'eating', 'food', 'hungry', 'meal', 'lunch', 'dinner', 'breakfast', 'snack', 'feed', 'bite', 'chew', 'swallow', 'taste', 'nutrition', 'appetite'],
  'drink': ['drink', 'drinking', 'thirsty', 'beverage', 'sip', 'gulp', 'swallow', 'liquid', 'fluid'],
  'water': ['water', 'h2o', 'agua', 'hydrate', 'hydration'],
  'toilet': ['toilet', 'bathroom', 'pee', 'poop', 'potty', 'restroom', 'washroom', 'lavatory', 'need', 'use'],
  'sleep': ['sleep', 'sleeping', 'tired', 'nap', 'rest', 'bed', 'bedtime', 'drowsy', 'sleepy', 'exhausted', 'doze'],
  'help': ['help', 'assist', 'aid', 'support', 'emergency', 'need', 'please', 'rescue', 'save'],
  'medicine': ['medicine', 'pill', 'medication', 'drug', 'dose', 'treatment', 'remedy', 'prescription', 'tablet'],
  'hungry': ['hungry', 'starving', 'famished', 'appetite', 'empty', 'want', 'need', 'food'],
  'thirsty': ['thirsty', 'parched', 'dry', 'dehydrated', 'want', 'need', 'drink'],
  'pain': ['pain', 'hurt', 'hurts', 'ache', 'aches', 'sore', 'ouch', 'ow', 'painful', 'injury', 'wound'],
  'hot': ['hot', 'warm', 'heat', 'sweating', 'sweat', 'burning', 'boiling', 'fever'],
  'cold': ['cold', 'chilly', 'freezing', 'cool', 'shivering', 'shiver', 'frozen', 'ice'],

  // Actions - expanded
  'play': ['play', 'playing', 'game', 'games', 'fun', 'toy', 'toys', 'entertainment', 'activity'],
  'walk': ['walk', 'walking', 'stroll', 'strolling', 'step', 'steps', 'move', 'go'],
  'run': ['run', 'running', 'jog', 'jogging', 'sprint', 'sprinting', 'race', 'racing', 'fast'],
  'sit': ['sit', 'sitting', 'seated', 'down', 'chair', 'rest'],
  'stand': ['stand', 'standing', 'up', 'getup', 'rise', 'upright'],
  'read': ['read', 'reading', 'book', 'books', 'story', 'stories', 'text'],
  'write': ['write', 'writing', 'written', 'pen', 'pencil', 'compose', 'type'],
  'draw': ['draw', 'drawing', 'art', 'paint', 'painting', 'color', 'coloring', 'sketch', 'create'],
  'listen': ['listen', 'listening', 'hear', 'hearing', 'sound', 'audio', 'ears'],
  'watch': ['watch', 'watching', 'see', 'seeing', 'look', 'looking', 'tv', 'television', 'video', 'show', 'movie'],
  'talk': ['talk', 'talking', 'speak', 'speaking', 'say', 'saying', 'chat', 'chatting', 'conversation', 'tell', 'communicate'],
  'sing': ['sing', 'singing', 'song', 'songs', 'music', 'melody', 'tune'],
  'dance': ['dance', 'dancing', 'boogie', 'groove', 'move', 'moves'],
  'jump': ['jump', 'jumping', 'hop', 'hopping', 'bounce', 'bouncing', 'leap'],

  // Feelings - expanded
  'happy': ['happy', 'glad', 'joyful', 'cheerful', 'good', 'great', 'wonderful', 'pleased', 'delighted', 'content', 'joy', 'smile', 'smiling'],
  'sad': ['sad', 'unhappy', 'down', 'blue', 'crying', 'cry', 'tears', 'upset', 'disappointed', 'gloomy', 'depressed'],
  'angry': ['angry', 'mad', 'upset', 'furious', 'rage', 'annoyed', 'irritated', 'cross', 'grumpy'],
  'scared': ['scared', 'afraid', 'frightened', 'fear', 'fearful', 'spooky', 'terrified', 'worried', 'anxious', 'nervous'],
  'excited': ['excited', 'thrilled', 'eager', 'pumped', 'enthusiastic', 'hyper', 'energetic'],
  'tired': ['tired', 'exhausted', 'sleepy', 'weary', 'fatigued', 'drained', 'worn'],
  'sick': ['sick', 'ill', 'unwell', 'nauseous', 'queasy', 'poorly', 'ailing'],
  'love': ['love', 'loving', 'adore', 'like', 'heart', 'affection', 'care', 'cherish'],
  'worried': ['worried', 'anxious', 'nervous', 'concerned', 'stress', 'stressed', 'tension'],
  'calm': ['calm', 'peaceful', 'relaxed', 'serene', 'tranquil', 'quiet', 'still'],
  'proud': ['proud', 'accomplished', 'achievement', 'success', 'successful', 'win'],
  'surprised': ['surprised', 'shocked', 'amazed', 'astonished', 'wow', 'incredible'],

  // People - expanded
  'mom': ['mom', 'mother', 'mama', 'mommy', 'mum', 'mummy', 'ma'],
  'dad': ['dad', 'father', 'papa', 'daddy', 'pop', 'dada'],
  'sister': ['sister', 'sis', 'sibling'],
  'brother': ['brother', 'bro', 'sibling'],
  'grandma': ['grandma', 'grandmother', 'nana', 'granny', 'gran', 'grandmom'],
  'grandpa': ['grandpa', 'grandfather', 'papa', 'gramps', 'granddad', 'pops'],
  'friend': ['friend', 'friends', 'buddy', 'pal', 'mate', 'companion'],
  'teacher': ['teacher', 'instructor', 'educator', 'tutor', 'coach', 'professor'],
  'doctor': ['doctor', 'physician', 'dr', 'nurse', 'medical', 'healthcare'],
  'baby': ['baby', 'infant', 'newborn', 'toddler', 'child'],
  'family': ['family', 'relatives', 'household', 'parents', 'siblings', 'kin'],
  'me': ['me', 'myself', 'i', 'my', 'mine', 'self'],
  'you': ['you', 'your', 'yours', 'yourself'],
  'boy': ['boy', 'lad', 'male'],
  'girl': ['girl', 'lass', 'female'],

  // Places - expanded
  'home': ['home', 'house', 'residence', 'apartment', 'dwelling', 'place'],
  'school': ['school', 'classroom', 'class', 'academy', 'education', 'learning'],
  'park': ['park', 'playground', 'outside', 'outdoors', 'nature', 'garden'],
  'hospital': ['hospital', 'clinic', 'medical', 'doctor', 'emergency'],
  'store': ['store', 'shop', 'market', 'grocery', 'supermarket', 'mall', 'shopping'],
  'restaurant': ['restaurant', 'cafe', 'diner', 'eatery', 'cafeteria', 'bistro'],
  'playground': ['playground', 'swings', 'slide', 'play', 'park'],
  'beach': ['beach', 'ocean', 'sand', 'seaside', 'shore', 'coast', 'sea'],
  'car': ['car', 'vehicle', 'automobile', 'drive', 'driving', 'ride', 'auto'],
  'bedroom': ['bedroom', 'room', 'bed'],
  'bathroom': ['bathroom', 'bath', 'shower', 'washroom', 'toilet', 'restroom'],
  'kitchen': ['kitchen', 'cook', 'cooking', 'food', 'prepare'],
  'outside': ['outside', 'outdoors', 'exterior', 'out'],
  'inside': ['inside', 'indoors', 'interior', 'in'],

  // Custom/Items - expanded
  'apple': ['apple', 'apples', 'fruit'],
  'banana': ['banana', 'bananas', 'fruit'],
  'pizza': ['pizza', 'slice', 'pie', 'food'],
  'juice': ['juice', 'drink', 'beverage'],
  'milk': ['milk', 'dairy', 'drink'],
  'cookie': ['cookie', 'cookies', 'biscuit', 'treat', 'sweet', 'dessert'],
  'toy': ['toy', 'toys', 'plaything', 'game'],
  'book': ['book', 'books', 'story', 'read'],
  'ball': ['ball', 'balls', 'sphere', 'toy'],
  'phone': ['phone', 'telephone', 'mobile', 'cell', 'call', 'smartphone'],
  'music': ['music', 'song', 'songs', 'tune', 'melody', 'sound'],
  'yes': ['yes', 'yeah', 'yep', 'ok', 'okay', 'sure', 'agree', 'correct', 'right', 'affirmative'],
  'no': ['no', 'nope', 'nah', 'not', 'never', 'disagree'],
  'please': ['please', 'kindly', 'plz', 'pls'],
  'thankyou': ['thank you', 'thanks', 'ty', 'thx', 'appreciate', 'grateful', 'gratitude'],
  'sorry': ['sorry', 'apologize', 'apology', 'regret', 'oops'],
  'do': ['do', 'doing', 'did', 'does', 'action', 'perform', 'execute'],
  'make': ['make', 'making', 'made', 'create', 'build', 'construct'],
  'want': ['want', 'desire', 'wish', 'would like', 'wanna'],
  'need': ['need', 'require', 'must have', 'necessary'],
  'like': ['like', 'enjoy', 'love', 'prefer', 'favorite'],
  'more': ['more', 'extra', 'additional', 'another', 'again'],
  'all': ['all done', 'finished', 'complete', 'end', 'stop', 'done'],
  'wait': ['wait', 'waiting', 'hold', 'pause', 'hold on'],
  'go': ['go', 'going', 'leave', 'depart', 'move'],
  'stop': ['stop', 'halt', 'cease', 'end', 'quit'],
  'now': ['now', 'right now', 'immediately', 'currently'],
  'later': ['later', 'after', 'soon', 'eventually'],
};
