/**
 * Norwegian Keyword Mappings for Icon Matcher
 * Norwegian translations and synonyms for AAC communication
 */

export const KEYWORD_MAP_NO: Record<string, string[]> = {
  // Needs - Behov
  'eat': ['spise', 'spiser', 'mat', 'sulten', 'måltid', 'lunsj', 'middag', 'frokost', 'snack', 'snacks', 'bite', 'tygge', 'svelge', 'smake', 'ernæring', 'matlyst'],
  'drink': ['drikke', 'drikker', 'tørst', 'drikk', 'væske', 'slurp', 'svelge', 'dram'],
  'water': ['vann', 'h2o', 'væske'],
  'toilet': ['toalett', 'do', 'baderom', 'tiss', 'bæsj', 'potte', 'wc', 'dass'],
  'sleep': ['sove', 'sover', 'søvn', 'sliten', 'hvile', 'lur', 'hvile', 'seng', 'sengetid', 'trøtt', 'utslitt', 'døsig'],
  'help': ['hjelp', 'hjelpe', 'assistanse', 'støtte', 'nødsituasjon', 'trenger', 'vær så snill', 'redning', 'redde'],
  'medicine': ['medisin', 'pille', 'medikament', 'dose', 'behandling', 'kur', 'resept', 'tablett'],
  'hungry': ['sulten', 'utsultet', 'matlyst', 'tom', 'vil ha', 'trenger', 'mat'],
  'thirsty': ['tørst', 'tørr', 'dehydrert', 'vil ha', 'trenger', 'drikke'],
  'pain': ['vondt', 'smerte', 'smerter', 'verk', 'øm', 'au', 'smertefullt', 'skade', 'sår'],
  'hot': ['varmt', 'varm', 'varme', 'svette', 'svetter', 'brenner', 'koker', 'feber'],
  'cold': ['kaldt', 'kald', 'frossen', 'kjølig', 'fryser', 'fryser', 'iskaldt', 'is'],

  // Actions - Handlinger
  'play': ['leke', 'leker', 'spill', 'moro', 'leke', 'leker', 'underholdning', 'aktivitet'],
  'walk': ['gå', 'går', 'spasere', 'rusle', 'steg', 'bevege', 'bevege seg'],
  'run': ['løpe', 'løper', 'jogge', 'sprinte', 'løp', 'kappløp', 'fort'],
  'sit': ['sitte', 'sitter', 'ned', 'stol', 'hvile'],
  'stand': ['stå', 'står', 'opp', 'reise seg', 'oppreist'],
  'read': ['lese', 'leser', 'bok', 'bøker', 'historie', 'tekst'],
  'write': ['skrive', 'skriver', 'penn', 'blyant', 'komponere', 'taste'],
  'draw': ['tegne', 'tegner', 'kunst', 'male', 'maling', 'farge', 'fargelegge', 'skisse', 'lage'],
  'listen': ['lytte', 'lytter', 'høre', 'hører', 'lyd', 'audio', 'ører'],
  'watch': ['se', 'ser', 'kikke', 'kikker', 'tv', 'televisjon', 'video', 'program', 'film'],
  'talk': ['snakke', 'snakker', 'prate', 'prater', 'si', 'sier', 'samtale', 'fortelle', 'kommunisere'],
  'sing': ['synge', 'synger', 'sang', 'sanger', 'musikk', 'melodi', 'tone'],
  'dance': ['danse', 'danser', 'bevege seg', 'groove'],
  'jump': ['hoppe', 'hopper', 'sprette', 'springe', 'bounce'],

  // Feelings - Følelser
  'happy': ['glad', 'lykkelig', 'fornøyd', 'fryd', 'glede', 'bra', 'fin', 'flott', 'strålende', 'smile', 'smiler'],
  'sad': ['trist', 'lei seg', 'ned', 'blå', 'gråter', 'gråte', 'tårer', 'opprørt', 'skuffet', 'nedfor', 'deprimert'],
  'angry': ['sint', 'rasende', 'sur', 'opprørt', 'irritert', 'gretten'],
  'scared': ['redd', 'engstelig', 'frykt', 'skremt', 'skummel', 'livredd', 'bekymret', 'nervøs'],
  'excited': ['spent', 'begeistret', 'ivrig', 'entusiastisk', 'energisk'],
  'tired': ['sliten', 'utslitt', 'søvnig', 'trøtt', 'utmattet', 'drenert', 'mødig'],
  'sick': ['syk', 'dårlig', 'kvalm', 'uvel'],
  'love': ['kjærlighet', 'elsker', 'glad i', 'hjerte', 'ømhet', 'bry seg', 'verdsette'],
  'worried': ['bekymret', 'engstelig', 'nervøs', 'urolig', 'stress', 'stresset', 'spent'],
  'calm': ['rolig', 'fredelig', 'avslappet', 'stille', 'harmonisk'],
  'proud': ['stolt', 'prestasjon', 'suksess', 'vellykket', 'seier'],
  'surprised': ['overrasket', 'sjokkert', 'forbauset', 'wow', 'utrolig'],

  // People - Personer
  'mom': ['mamma', 'mor', 'mama', 'mutter'],
  'dad': ['pappa', 'far', 'papa', 'daddy'],
  'sister': ['søster', 'søsken'],
  'brother': ['bror', 'søsken'],
  'grandma': ['bestemor', 'mormor', 'farmor', 'gammelmor'],
  'grandpa': ['bestefar', 'morfar', 'farfar', 'gammellfar'],
  'friend': ['venn', 'venner', 'kompis', 'kamerat'],
  'teacher': ['lærer', 'instruktør', 'pedagog', 'trener', 'coach', 'professor'],
  'doctor': ['lege', 'doktor', 'dr', 'sykepleier', 'medisinsk', 'helse'],
  'baby': ['baby', 'spedbarn', 'nyfødt', 'småbarn', 'barn'],
  'family': ['familie', 'slekt', 'husstand', 'foreldre', 'søsken'],
  'me': ['meg', 'jeg', 'min', 'mitt', 'mine', 'selv'],
  'you': ['deg', 'du', 'din', 'ditt', 'dine'],
  'boy': ['gutt', 'guttunge', 'guttebarn'],
  'girl': ['jente', 'jenteunge', 'jentebarn'],

  // Places - Steder
  'home': ['hjem', 'hjemme', 'hus', 'bolig', 'leilighet', 'sted'],
  'school': ['skole', 'klasserom', 'klasse', 'akademi', 'utdanning', 'læring'],
  'park': ['park', 'lekeplass', 'ute', 'utenfor', 'natur', 'hage'],
  'hospital': ['sykehus', 'klinikk', 'medisinsk', 'lege', 'akutt'],
  'store': ['butikk', 'handel', 'marked', 'dagligvare', 'supermarked', 'kjøpesenter', 'shopping'],
  'restaurant': ['restaurant', 'kafé', 'spisested', 'kafeteria', 'bistro'],
  'playground': ['lekeplass', 'huske', 'sklie', 'leke', 'park'],
  'beach': ['strand', 'hav', 'sand', 'sjø', 'kyst'],
  'car': ['bil', 'kjøretøy', 'automobil', 'kjøre', 'kjører', 'reise', 'tur'],
  'bedroom': ['soverom', 'rom', 'seng'],
  'bathroom': ['baderom', 'bad', 'dusj', 'toalett', 'wc'],
  'kitchen': ['kjøkken', 'lage mat', 'matlaging', 'mat', 'tilberede'],
  'outside': ['ute', 'utenfor', 'utendørs'],
  'inside': ['inne', 'innendørs'],

  // Custom/Items - Tilpasset
  'apple': ['eple', 'epler', 'frukt'],
  'banana': ['banan', 'bananer', 'frukt'],
  'pizza': ['pizza', 'pizzastykke', 'mat'],
  'juice': ['juice', 'saft', 'drikke'],
  'milk': ['melk', 'meieri', 'drikke'],
  'cookie': ['cookie', 'cookies', 'kjeks', 'godteri', 'søtt', 'dessert'],
  'toy': ['leke', 'leker', 'leketøy', 'spill'],
  'book': ['bok', 'bøker', 'historie', 'lese'],
  'ball': ['ball', 'kuле', 'leke'],
  'phone': ['telefon', 'mobil', 'ringe', 'smarttelefon'],
  'music': ['musikk', 'sang', 'sanger', 'tone', 'melodi', 'lyd'],
  'yes': ['ja', 'jada', 'ok', 'okay', 'greit', 'enig', 'riktig', 'stemmer'],
  'no': ['nei', 'niks', 'ikke', 'aldri', 'uenig'],
  'please': ['vær så snill', 'takk', 'vennligst', 'please'],
  'thankyou': ['takk', 'tusen takk', 'mange takk', 'takknemlig'],
  'sorry': ['beklager', 'unnskyld', 'lei meg'],
  'do': ['gjøre', 'gjør', 'gjort', 'handle', 'utføre'],
  'make': ['lage', 'lager', 'lagde', 'skaper', 'skape', 'bygge'],
  'want': ['vil ha', 'ønsker', 'vil', 'ønske'],
  'need': ['trenger', 'må ha', 'behov'],
  'like': ['liker', 'elsker', 'glad i', 'favoritt'],
  'more': ['mer', 'ekstra', 'flere', 'enda'],
  'all': ['ferdig', 'slutt', 'alt', 'all', 'alle'],
  'wait': ['vent', 'vente', 'venter', 'hold'],
  'go': ['gå', 'dra', 'reise', 'bevege seg', 'kjør'],
  'stop': ['stopp', 'slutt', 'stans', 'hold'],
  'now': ['nå', 'akkurat nå', 'med en gang'],
  'later': ['senere', 'etterpå', 'straks'],
};
